---
- name: "Ensure remote helm value file values are set"
  ansible.builtin.slurp:
    src: "{{ __k4k8s_cm_remote_helm_value_file__ }}"
  register: "__k4k8s_cm_slurped_values__"

- name: "Ensure '__k4k8s_cm_remote_helm_value_file__' values are available"
  ansible.builtin.set_fact:
    __k4k8s_cm_helm_release_values__: "{{ __k4k8s_cm_helm_release_values__ | combine(__k4k8s_cm_slurped_values__['content'] |
                                              b64decode | from_yaml) }}"
