---
# Helm3
k4k8s_deploy_helm_atomic: false
k4k8s_deploy_helm_binary_path: "{{ k4k8s_deploy_bin_version_info['helm']['destination'] }}/helm"
k4k8s_deploy_helm_chart_ref: "kong/kong"
k4k8s_deploy_helm_chart_repo_name: "kong"
k4k8s_deploy_helm_chart_repo_url: "https://charts.konghq.com"
# k4k8s_deploy_helm_chart_repo_username: ""
# k4k8s_deploy_helm_chart_repo_password: ""
# k4k8s_deploy_helm_chart_version: "v2.8.2"
k4k8s_deploy_helm_disable_hook: false
k4k8s_deploy_helm_force_reinstall: false
k4k8s_deploy_helm_release_name: "kong"
k4k8s_deploy_helm_replace: false
k4k8s_deploy_helm_update_repo: true
k4k8s_deploy_helm_wait: true
