---
- name: "Ensure kong enterprise license secret is present"
  ansible.builtin.include_tasks: "kubernetes_install/secrets/kong_enterprise_license.yml"
  when: "k4k8s_deploy_create_enterprise_license_secret | default(False) | bool"

- name: "Ensure kong enterprise superuser password secret is present"
  ansible.builtin.include_tasks: "kubernetes_install/secrets/superuser_password.yml"
  when: "k4k8s_deploy_create_enterprise_superuser_password_secret | default(False) | bool"

- name: "Ensure kong enterprise postgresql password secret is present"
  ansible.builtin.include_tasks: "kubernetes_install/secrets/postgres_password.yml"
  when: "k4k8s_deploy_create_postgres_password_secret | default(False)| bool"

- name: "Ensure kong enterprise sessions secret is present"
  ansible.builtin.include_tasks: "kubernetes_install/secrets/kong_sessions.yml"
  when: (k4k8s_deploy_create_admin_gui_sessions_conf_secret | default(False) | bool) or
        (k4k8s_deploy_create_portal_sessions_conf_secret | default(False) | bool)

- name: "Ensure kong enterprise hybrid-mode secret is present"
  ansible.builtin.include_tasks: "kubernetes_install/secrets/hybrid_mode.yml"
  when: (k4k8s_deploy_create_hybrid_mode_cp_cert_secret | bool) or
        (k4k8s_deploy_create_hybrid_mode_dp_cert_secret | bool)
