---
- name: "Ensure kong enterprise license secret is present"
  kubernetes.core.k8s:
    state: "present"
    definition: "{{ lookup('template', 'templates/secret-kong-enterprise-license.yaml.j2' | from_yaml) }}"