---
- name: "Ensure kong enterprise postgresql password secret is present"
  kubernetes.core.k8s:
    state: "present"
    definition: "{{ lookup('template', 'templates/secret-postgres-password.yaml.j2' | from_yaml) }}"