---
- name: "Ensure kong enterprise superuser password secret is present"
  kubernetes.core.k8s:
    state: "present"
    definition: "{{ lookup('template', 'templates/secret-kong-enterprise-bootstrap-password.yaml.j2' | from_yaml) }}"