---
- name: "Ensure namespace is present | {{ k4k8s_edns_namespace }}"
  kubernetes.core.k8s:
    name: "{{ k4k8s_edns_namespace }}"
    api_version: "v1"
    context: "{{ k4k8s_cluster_context | default(omit) }}"
    kind: "Namespace"
    kubeconfig: "{{ k4k8s_kubeconfig | default(omit) }}"
    state: "present"

- name: "Ensure external-dns is present | local helm values"
  ansible.builtin.include_tasks: "deployment.yml"
  delegate_to: "localhost"
  when: "not k4k8s_edns_helm_chart_values_remote | bool"

- name: "Ensure external-dns is present | remote helm values"
  ansible.builtin.include_tasks: "deployment.yaml"
  when: "k4k8s_edns_helm_chart_values_remote | bool"