---
- name: "Ensure {{ k4k8s_helm_component_name }} helm chart values are available"
  ansible.builtin.include_tasks: "helm_values/collect_helm_values.yml"

- name: "Ensure {{ k4k8s_helm_component_name }} is present"
  kubernetes.core.helm:
    atomic: "{{ k4k8s_helm_atomic }}"
    binary_path: "{{ k4k8s_helm_binary_path }}"
    chart_ref: "{{ k4k8s_helm_chart_ref }}"
    chart_version: "{{ k4k8s_helm_chart_version | default(omit) }}"
    context: "{{ k4k8s_cluster_context | default(omit) }}"
    create_namespace: false
    disable_hook: "{{ k4k8s_helm_disable_hook }}"
    force: "{{ k4k8s_helm_force_reinstall }}"
    kubeconfig: "{{ k4k8s_kubeconfig | default(omit) }}"
    release_name: "{{ k4k8s_helm_release_name }}"
    release_namespace: "{{ k4k8s_helm_release_namespace }}"
    release_state: "present"
    release_values: "{{ __k4k8s_helm_release_values__ }}"
    replace: "{{ k4k8s_helm_replace }}"
    skip_crds: false
    update_repo_cache: "{{ k4k8s_helm_update_repo }}"
    wait: "{{ k4k8s_helm_wait }}"
  register: "__k4k8s_helm_results__"