---
- name: "Ensure kong for kubernetes is present | helm"
  ansible.builtin.include_role:
    name: "common/k4k8s_helm"
    public: true
  vars:
    k4k8s_helm_atomic: "{{ k4k8s_deploy_helm_atomic }}"
    k4k8s_helm_binary_path: "{{ k4k8s_deploy_helm_binary_path }}"
    k4k8s_helm_chart_values: "{{ k4k8s_deploy_helm_chart_values }}"
    k4k8s_helm_chart_values_files: "{{ k4k8s_deploy_helm_chart_values_files }}"
    k4k8s_helm_chart_values_remote: "{{ k4k8s_deploy_helm_chart_values_remote }}"
    k4k8s_helm_chart_version: "{{ k4k8s_deploy_helm_chart_version | default(None) }}"
    k4k8s_helm_chart_ref: "{{ k4k8s_deploy_helm_chart_ref }}"
    k4k8s_helm_chart_repo_name: "{{ k4k8s_deploy_helm_chart_repo_name }}"
    k4k8s_helm_chart_repo_password: "{{ k4k8s_deploy_helm_chart_repo_password | default(None) }}"
    k4k8s_helm_chart_repo_url: "{{ k4k8s_deploy_helm_chart_repo_url }}"
    k4k8s_helm_chart_repo_username: "{{ k4k8s_deploy_helm_chart_repo_username | default(None) }}"
    k4k8s_helm_component_name: "kong for kubernetes"
    k4k8s_helm_disable_hook: "{{ k4k8s_deploy_helm_disable_hook }}"
    k4k8s_helm_force_reinstall: "{{ k4k8s_deploy_helm_force_reinstall }}"
    k4k8s_helm_release_name: "{{ k4k8s_deploy_helm_release_name }}"
    k4k8s_helm_release_namespace: "{{ k4k8s_deploy_namespace }}"
    k4k8s_helm_replace: "{{ k4k8s_deploy_helm_replace }}"
    k4k8s_helm_update_repo: "{{ k4k8s_deploy_helm_update_repo }}"
    k4k8s_helm_wait: "{{ k4k8s_deploy_helm_wait }}"

- name: "Set collected helm run facts"
  ansible.builtin.set_fact:
    __k4k8s_deploy_helm_results__: "{{ __k4k8s_helm_results__ }}"
    __k4k8s_deploy_helm_release_values__: "{{ __k4k8s_helm_release_values__ }}"
