---
- name: "Deploy kong for kubernetes prerequisite components"
  module_defaults:
    kubernetes.core.k8s_info:
      wait: True
      wait_timeout: 600
      kubeconfig: "{{ k4k8s_deploy_kubeconfig | default(omit) }}"
      context: "{{ k4k8s_deploy_cluster_context | default(omit) }}"
    kubernetes.core.k8s:
      wait: True
      wait_timeout: 600
      kubeconfig: "{{ k4k8s_deploy_kubeconfig | default(omit) }}"
      context: "{{ k4k8s_deploy_cluster_context | default(omit) }}"
  block:
    - name: "Ensure Kong namespace is present | {{ k4k8s_deploy_namespace }}"
      kubernetes.core.k8s:
        name: "{{ k4k8s_deploy_namespace }}"
        api_version: "v1"
        kind: "Namespace"
        state: "present"
    
    - name: "Ensure kong for kubernetes secrets are present"
      ansible.builtin.include_tasks: "kubernetes_install/secrets/create_secrets.yml"
      when: ("k4k8s_deploy_create_enterprise_license_secret | default(False) | bool") or
            ("k4k8s_deploy_create_enterprise_bootstrap_password_secret | default(False) | bool") or
            ("k4k8s_deploy_create_hybrid_mode_cp_cert_secret | default(False) | bool") or
            ("k4k8s_deploy_create_hybrid_mode_dp_cert_secret | default(False) | bool") or
            ("k4k8s_deploy_create_postgres_password_secret | default(False) | bool") or
            ("k4k8s_deploy_create_admin_gui_sessions_conf_secret| default(False) | bool") or
            ("k4k8s_deploy_create_portal_gui_sessions_conf_secret| default(False) | bool")