---
- name: "Fail when deploy method is not properly set"
  ansible.builtin.fail:
    msg:
      - "k4k8s_deploy_method must be one of 'helm' or 'yaml_manifest'"
      - "You specified: {{ k4k8s_deploy_method }}"
  when:
    - "k4k8s_deploy_method != 'helm'"
    - "k4k8s_deploy_method != 'yaml_manifest'"
  tags:
    - "deploy"
    - "deploy_k4k8s"

- name: "Install python dependencies"
  ansible.builtin.include_tasks: "prerequisite_install/py_prereqs.yml"
  when: "k4k8s_deploy_install_python_dependencies | bool"
  tags:
    - "install_deps"
    - "install_python_deps"

- name: "Validate python dependencies"
  ansible.builtin.include_tasks: "validate/call_chk_py_prereqs.yml"
  when: "k4k8s_deploy_validate_python_dependencies | bool"
  tags:
    - "validate_deps"
    - "validate_python_deps"

- name: "Ensure hybrid mode certificate ansible collection dependencies are included"
  ansible.builtin.set_fact:
    k4k8s_deploy_ansible_collection_deps: "{{ k4k8s_deploy_ansible_collection_deps | union(k4k8s_deploy_ansible_collection_deps_hybrid_certs) }}"
  when: (k4k8s_deploy_install_ansible_collection_dependencies | bool and k4k8s_deploy_create_hybrid_mode_cp_cert_secret | bool) or
        (k4k8s_deploy_validate_ansible_collection_dependencies | bool and k4k8s_deploy_create_hybrid_mode_cp_cert_secret | bool)
  tags:
    - "install_deps"
    - "install_collection_deps"

- name: "Install ansible collection dependencies"
  ansible.builtin.include_tasks: "prerequisite_install/ansible_collection_prereqs.yml"
  when: "k4k8s_deploy_install_ansible_collection_dependencies | bool"
  tags:
    - "install_deps"
    - "install_collection_deps"

- name: "Validate ansible collection dependencies"
  ansible.builtin.include_tasks: "validate/call_chk_ansible_collection_prereqs.yml"
  when: "k4k8s_deploy_validate_ansible_collection_dependencies | bool"
  tags:
    - "validate_deps"
    - "validate_collection_deps"

- name: "Ensure helm dependencies are included"
  ansible.builtin.set_fact:
    k4k8s_deploy_bin_deps: "{{ k4k8s_deploy_bin_deps | union(k4k8s_deploy_bin_deps_helm_method) }}"
    k4k8s_deploy_install_bin_tarballs: "{{ k4k8s_deploy_install_bin_tarballs | union(k4k8s_deploy_install_bin_tarballs_helm_method) }}"
  when: "k4k8s_deploy_method == 'helm'"
  tags:
    - "install_deps"
    - "install_binary_deps"

- name: "Install binary dependencies"
  ansible.builtin.include_tasks: "prerequisite_install/bin_prereqs.yml"
  when: "k4k8s_deploy_install_binary_dependencies | bool"
  tags:
    - "install_deps"
    - "install_binary_deps"

- name: "Validate binary dependencies"
  ansible.builtin.include_tasks: "validate/call_chk_bin_prereqs.yml"
  when: "k4k8s_deploy_validate_binary_dependencies | bool"
  tags:
    - "validate_deps"
    - "validate_binary_deps"

- name: "Ensure kong for kubernetes prereqisite components are deployed"
  ansible.builtin.include_tasks: "kubernetes_install/prerequisite.yml"
  tags:
    - "deploy"
    - "deploy_k4k8s_kubernetes_prereqs"

- name: "Ensure kong for kubernetes is present | {{ k4k8s_deploy_method }}"
  ansible.builtin.include_tasks: "kubernetes_install/{{ k4k8s_deploy_method }}.yml"
  tags:
    - "deploy"
    - "deploy_k4k8s"