---
- name: "Fail when deploy method is not properly set"
  ansible.builtin.fail:
    msg:
      - "k4k8s_deploy_method must be one of 'helm' or 'yaml_manifest'"
      - "You specified: {{ k4k8s_deploy_method }}"
  when:
    - "k4k8s_deploy_method != 'helm'"
    - "k4k8s_deploy_method != 'yaml_manifest'"
  tags:
    - "deploy"
    - "deploy_k4k8s"

- name: "Ensure kong for kubernetes prereqisite components are deployed"
  ansible.builtin.include_tasks: "kubernetes_install/prerequisite.yml"
  tags:
    - "deploy"
    - "deploy_k4k8s_kubernetes_prereqs"

- name: "Ensure kong for kubernetes is present | {{ k4k8s_deploy_method }}"
  ansible.builtin.include_tasks: "kubernetes_install/{{ k4k8s_deploy_method }}.yml"
  tags:
    - "deploy"
    - "deploy_k4k8s"
