---
- name: "Collect currently installed CRDs from the cluster"
  kubernetes.core.k8s_info:
    context: "{{ k4k8s_cluster_context | default(omit) }}"
    kind: "CustomResourceDefinition"
    kubeconfig: "{{ k4k8s_kubeconfig | default(omit) }}"
  register: "__k4k8s_cm_installed_crds__"

- name: "Set initial CRD validation list"
  ansible.builtin.set_fact:
    __k4k8s_cm_crd_status__: "{{ __k4k8s_cm_installed_crds__['resources'] | json_query('[*].metadata.name') }}"
    __k4k8s_cm_crd_missing__: []

- name: "Validate jetstack cert-manager CRDs are present"
  ansible.builtin.include_tasks: "preflight/chk_crd.yml"
  with_items: "{{ k4k8s_cm_crd_names }}"
  loop_control:
    loop_var: "__k4k8s_cm_crd__"