---
name: "release"
"on":
  release:
    types:
      - "published"

jobs:
  release-collection:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Publish the collection to Ansible Galaxy
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"